# 1. Count The Number Of Times Each Value Appears In An Array Of Integers

In [7]:
import numpy as np
arr = np.random.randint(1,10,20)
print(arr)
print(np.bincount(arr))

[4 2 4 4 3 2 8 7 9 6 4 8 9 4 3 6 5 5 1 9]
[0 1 2 2 5 2 2 1 2 3]


# 2. Given 9 Integers. You have to convert them into 3*3 Numpy array using Reshape function.

In [2]:
arr = np.random.randint(1,10,9)
arr.reshape(3,3)

array([[5, 1, 6],
       [9, 8, 6],
       [2, 7, 9]])

# 3. How to find the memory size of any array

In [4]:
print(arr.size*arr.itemsize,"bytes")

36 bytes


# 4. Create a 2d array of size 10 by 10 with 1 on the border and 0 inside.

In [5]:
arr = np.ones((10,10))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 5.Create a 8x8 matrix and fill it with a checkerboard pattern.

In [6]:
checB = np.ones((8,8))
checB[1::2,::2] = 0
checB[::2,1::2] = 0
print(checB)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


# 6. Normalize a 5x5 random matrix.

In [7]:
mat = np.random.randint(1,50,(5,5))
(mat-np.mean(mat))/np.std(mat)

array([[-0.76065165, -0.26885101, -0.43278456, -1.33441906,  1.94425184],
       [ 0.22294962, -0.67868488,  0.96065057, -0.10491747,  0.96065057],
       [-0.51475133,  0.55081671, -1.25245228,  0.79671703,  1.20655089],
       [-1.08851874, -1.08851874,  2.43605248,  1.20655089, -0.67868488],
       [-0.76065165, -0.76065165, -0.35081779, -0.5967181 ,  0.38688317]])

# 7. Given a 1D array in range(0,11), negate all elements which are between 3 and 8, in place.

In [9]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10,11])
for i in range(len(arr)):
    if 3<arr[i]<8:
        arr[i] = -arr[i]

        
print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11]


# 8. How to get the dates of yesterday, today and tomorrow?

In [10]:
print("Yesterday: ",np.datetime64('today','D')-np.timedelta64(1,'D'))
print("Today: ",np.datetime64('today','D'))
print("Tomorrow: ",np.datetime64('today','D')+np.timedelta64(1,'D'))

Yesterday:  2020-02-23
Today:  2020-02-24
Tomorrow:  2020-02-25


# 9. Generate two arrays of size 2X4 & 3X3, find difference between them.

In [11]:
array1 = np.random.randint(1,10,(2,4))
array2 = np.random.randint(1,15,(3,3))
array1.reshape(1,2,1,4) - array2.reshape(3,1,3,1)

array([[[[ 2,  0,  0,  0],
         [ 2,  0,  0,  0],
         [-3, -5, -5, -5]],

        [[-4,  1,  2,  0],
         [-4,  1,  2,  0],
         [-9, -4, -3, -5]]],


       [[[ 5,  3,  3,  3],
         [ 7,  5,  5,  5],
         [ 5,  3,  3,  3]],

        [[-1,  4,  5,  3],
         [ 1,  6,  7,  5],
         [-1,  4,  5,  3]]],


       [[[ 7,  5,  5,  5],
         [ 3,  1,  1,  1],
         [-2, -4, -4, -4]],

        [[ 1,  6,  7,  5],
         [-3,  2,  3,  1],
         [-8, -3, -2, -4]]]])

# 10. Given 1d array of ['cat','dog','rat'], genrate 100 elements of 1d array consisting of the above 3 value ?

['cat','cat',...,'rat','dog','dog','cat'...]


In [12]:
arr = ['cat','dog','rat']
np.random.choice(array,100)

array(['cat', 'dog', 'cat', 'cat', 'rat', 'cat', 'cat', 'rat', 'cat',
       'rat', 'dog', 'dog', 'cat', 'cat', 'dog', 'cat', 'rat', 'rat',
       'cat', 'cat', 'rat', 'rat', 'cat', 'rat', 'cat', 'rat', 'dog',
       'cat', 'rat', 'dog', 'cat', 'rat', 'dog', 'rat', 'cat', 'dog',
       'rat', 'rat', 'dog', 'rat', 'rat', 'rat', 'cat', 'dog', 'cat',
       'dog', 'dog', 'rat', 'rat', 'rat', 'cat', 'cat', 'cat', 'cat',
       'rat', 'rat', 'rat', 'dog', 'rat', 'dog', 'rat', 'dog', 'cat',
       'dog', 'rat', 'rat', 'dog', 'dog', 'rat', 'cat', 'cat', 'cat',
       'rat', 'rat', 'dog', 'rat', 'dog', 'dog', 'rat', 'dog', 'rat',
       'cat', 'rat', 'cat', 'rat', 'cat', 'cat', 'cat', 'dog', 'dog',
       'rat', 'cat', 'dog', 'dog', 'cat', 'rat', 'rat', 'rat', 'dog',
       'rat'], dtype='<U3')

# 11. Create a vector of size 10 with values ranging from 0 to 1, both excluded without manually deducing the values

In [13]:
vect = np.linspace(0,1,12)[1:-1]
print(vect)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


# 12. Given a two dimensional array, how to extract unique rows?

In [15]:
arr = np.random.randint(0,50,(5,5))
print(arr)
print("\n")
print(arr[[1]])

[[ 0 19 17  7 32]
 [ 6 28 35  5 10]
 [14 25 40 44 24]
 [ 5 29 46 40 28]
 [36 11 26 15 10]]


[[ 6 28 35  5 10]]


# 13. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area.

In [23]:
arr = np.zeros((3,3), [('x',float),('y',float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,3),np.linspace(0,1,3))
print(arr)

[[(0. , 0. ) (0.5, 0. ) (1. , 0. )]
 [(0. , 0.5) (0.5, 0.5) (1. , 0.5)]
 [(0. , 1. ) (0.5, 1. ) (1. , 1. )]]


# 14. How to find the closest value (to a given scalar) in a vector?

In [16]:
vect = np.arange(100)
scalar = np.random.uniform(0,100)
print(vect)
print(scalar)
index = (np.abs(vect-scalar)).argmin()
print(index)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
84.9833105322328
85


# 15. Consider a random vector with shape (10,2) representing coordinates, find point by point distances. Use euclidian distance.

In [17]:
random_vect = np.random.randint(0,10,(10,2))
x = random_vect[:,0]
y= random_vect[:,1]
print(x-y)

[ 3  2  3  4  0 -9  2 -3 -1  2]


# 16. How to sort an array by the nth column?

In [19]:
arr = np.random.randint(0,100,(5,5))
print(arr)
print("\n")
print(arr[arr[:,4].argsort()])

[[37 15 81 70  9]
 [69 67 49 26 67]
 [20 86 98 96 17]
 [86  1 60 71 18]
 [85 54 69 10  7]]


[[85 54 69 10  7]
 [37 15 81 70  9]
 [20 86 98 96 17]
 [86  1 60 71 18]
 [69 67 49 26 67]]


# 17.How to tell if a given 2D array has null columns?

In [20]:
arr = np.random.randint(1,10,(5,5))
np.isnan(arr)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

# 18. Considering a two dimensions array, how to get sum over the last two columns at once?


In [21]:
arr = np.random.randint(1,10,(5,5))
print(arr)
print(np.sum(arr[:,-2:]))

[[8 1 6 3 3]
 [1 5 7 8 5]
 [9 9 7 6 2]
 [8 3 2 8 4]
 [5 1 6 4 5]]
48


# 19. Given a 2d array of 5X5, increment 1st column by 1, second column by 2, 3rd column by 3 & so on till the last column

In [9]:
arr = np.random.randint(1,10,(5,5))
print(arr)
for i in range(len(arr)):
    arr[:,i] += i+1
print(arr)

[[7 5 9 7 4]
 [8 8 8 9 6]
 [8 3 6 4 9]
 [6 2 7 3 4]
 [4 3 8 4 7]]
[[ 8  7 12 11  9]
 [ 9 10 11 13 11]
 [ 9  5  9  8 14]
 [ 7  4 10  7  9]
 [ 5  5 11  8 12]]


# 20. Given a 1d array(size 100) of boolean values, identify total number of True in it.¶

In [11]:
arr = np.random.choice([True,False],100)
np.count_nonzero(arr)

56

# 21. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?¶

In [12]:
vect = np.array([1, 2, 3, 4, 5])
n = 3
new_vect = np.zeros(len(vect)+(len(vect)-1)*n)
print(new_vect)
new_vect[::n+1]=vect
print(new_vect)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


# 22. How to swap two rows of an array?

In [17]:
arr = np.random.randint(1,10,(10,10))
print(arr)
print("\n")
arr[[1,5]] = arr[[5,1]]
print(arr)

[[1 3 4 1 6 2 4 9 5 5]
 [5 5 2 9 5 3 9 1 2 8]
 [5 6 6 2 3 2 1 7 7 4]
 [8 3 5 5 7 4 3 4 6 6]
 [4 3 2 7 7 8 4 7 1 1]
 [5 1 5 3 4 1 3 8 9 3]
 [6 8 9 9 2 1 7 5 3 4]
 [6 4 7 9 2 9 8 8 2 2]
 [5 5 7 6 6 3 8 7 9 6]
 [9 3 4 8 2 9 9 6 8 3]]


[[1 3 4 1 6 2 4 9 5 5]
 [5 1 5 3 4 1 3 8 9 3]
 [5 6 6 2 3 2 1 7 7 4]
 [8 3 5 5 7 4 3 4 6 6]
 [4 3 2 7 7 8 4 7 1 1]
 [5 5 2 9 5 3 9 1 2 8]
 [6 8 9 9 2 1 7 5 3 4]
 [6 4 7 9 2 9 8 8 2 2]
 [5 5 7 6 6 3 8 7 9 6]
 [9 3 4 8 2 9 9 6 8 3]]


# 24. How to get n largest value of an array?

In [19]:
n = 5
arr = np.random.randint(1,20,20)
print(arr)
arr.sort()
print(arr[-n:])

[ 6  5  2 17 19 18  6 12  8  4  5  4 12 15  4  1  8  2 15 13]
[15 15 17 18 19]


# 25. Given two random arrays of shape 5X5, identify the common elements between them.

In [21]:
arr1 = np.random.randint(1,20,(5,5))
arr2 = np.random.randint(1,25,(5,5))
print(arr1)
print("\n")
print(arr2)
print("\n")
print(np.intersect1d(arr1,arr2))

[[19  1  6  3  5]
 [13  1  5 12  8]
 [ 4 13 18 15  7]
 [14 13  1  6  1]
 [11  9 18 19  8]]


[[20 21 21 17  1]
 [12 24  3  9  4]
 [ 5  8 19 24  4]
 [15 15  4  9 11]
 [13 13  1 24  9]]


[ 1  3  4  5  8  9 11 12 13 15 19]


# 26. How to get index of top two highest value in a 1d array?

In [22]:
arr = np.random.randint(1,10,12)
print(arr)
arr.argsort()[-2:]

[4 9 9 8 7 3 3 3 8 4 6 5]


array([1, 2], dtype=int64)